# Manipulating tensors

Tensor operations include: 

* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication


In [55]:
import torch
tensor = torch.arange(4, 10)
tensor

tensor([4, 5, 6, 7, 8, 9])

In [56]:
tensor + 10

tensor([14, 15, 16, 17, 18, 19])

In [57]:
tensor * 10


tensor([40, 50, 60, 70, 80, 90])

In [58]:
tensor - 10

tensor([-6, -5, -4, -3, -2, -1])

In [59]:
tensor / 10 

tensor([0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000])

We also have some built-in functions for above operations

`torch.mul()` , `torch.sub()` , `torch.add()` , `torch.div()`

## Matrix multiplication




In [60]:
# element-wise multiplication
tensor = torch.arange(0,10)
tensor * tensor

tensor([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [61]:
# Dot product
torch.matmul(tensor,tensor)

tensor(285)

### Matrix multiplication

We can use either `torch.matmul()` or `torch.mm()`

In [62]:
tensor = torch.rand([3,4])
tensor1 = torch.rand([4,3])

In [63]:
torch.matmul(tensor,tensor1)

tensor([[0.4395, 1.1458, 0.6249],
        [0.3828, 1.3621, 0.7304],
        [0.7911, 2.1748, 1.0153]])

In [64]:
#  Transpose of a matrix 
tensor , tensor.T

(tensor([[0.8762, 0.0244, 0.3334, 0.3508],
         [0.1163, 0.8896, 0.7305, 0.2842],
         [0.4743, 0.8981, 0.6837, 0.8486]]),
 tensor([[0.8762, 0.1163, 0.4743],
         [0.0244, 0.8896, 0.8981],
         [0.3334, 0.7305, 0.6837],
         [0.3508, 0.2842, 0.8486]]))

## finding the min, max, mean, sum, etc (tensor aggregation)

In [65]:
# Create a tensor 
x = torch.arange(0,100,10)
torch.min(x)
# x.min() also do the same thing

tensor(0)

In [66]:
torch.max(x)
# x.max() also do the same thing

tensor(90)

In [67]:
# Before perforing the mean, we should change the datatype to float
x.type(torch.float32).mean(), torch.mean(x.type(torch.float32))

(tensor(45.), tensor(45.))

In [68]:
#Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional max and min

In [69]:
x.argmax()

tensor(9)

In [70]:
x.argmin()

tensor(0)

## Reshaping, stacking, squezzing and unsquizzing tensors 

* Reshaping - reshapes an input tensor to a defined shape 
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor 
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all 1 dimensions from a tensor
* Unsqueeze - add a 1 dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted in a certain way

In [71]:
# Reshaping a tensor
tensor = torch.arange(1,13)
tensor.shape

torch.Size([12])

### Reshape

In [72]:
# With reshape method of tensor class we can reshape the tensor to any arbitrary tensor if valid (The  shape of the outpu tensor is compatible)
tensor.reshape([3,4])

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

### View

In [73]:
# View is exactly like reshape, but the new tensor is stored in the original tensor.
z = tensor.view(3,4)
z

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [74]:
# Changing z -----> changing original tensor
z[: , 0] = 5
z, tensor

(tensor([[ 5,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 5, 10, 11, 12]]),
 tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  5, 10, 11, 12]))

### Stack

In [75]:
# we use stack to put together some tensors. with dim=0 we stack them verticaly, with dim=1 we stack them horizontally 
tensor_stacked = torch.stack([x,x,x,x], dim=1)

In [76]:
tensor_stacked,tensor_stacked.shape

(tensor([[ 0,  0,  0,  0],
         [10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30],
         [40, 40, 40, 40],
         [50, 50, 50, 50],
         [60, 60, 60, 60],
         [70, 70, 70, 70],
         [80, 80, 80, 80],
         [90, 90, 90, 90]]),
 torch.Size([10, 4]))

### Squeezing and unsqueezing

In [77]:
# torch.unsqueeze adds a single dimension to the target tensor
x = torch.arange(0,100,5)
y = x.unsqueeze(dim=0)
y.shape

torch.Size([1, 20])

In [78]:
# In contrast, torch.squeeze removes the single dimension from the target tensor
z = y.squeeze(dim=0)
z.shape

torch.Size([20])

### Permute

In [79]:
# permute allows to change the dimension order of the tensor
x_original = torch.rand(size=(224,224,3))
x_permuted = x_original.permute(2,0,1)

print(f"Previous shape of the tensor: {x_original.shape}")
print(f"New shape of the tensor: {x_permuted.shape}")

Previous shape of the tensor: torch.Size([224, 224, 3])
New shape of the tensor: torch.Size([3, 224, 224])


## Indexing

In [81]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [82]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [86]:
x[0, :, :]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [88]:
x[:,1,:]

tensor([[4, 5, 6]])

In [89]:
x[:,:,2]

tensor([[3, 6, 9]])

In [90]:
x[:,-1,-1]

tensor([9])

In [91]:
x[:,:,-1]

tensor([[3, 6, 9]])

## PyTorch tensors and NumPy
* To change the data from NumPy array to tensor in PyTorch ----> `torch.from_numpy(ndarray)`
* To change the data from tensor to NumPy array ----> `torch.Tensor.numpy()`

In [97]:
import numpy as np

array = np.arange(1.,10.)
tensor = torch.from_numpy(array)
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [99]:
torch.arange(0.,10.).dtype

torch.float32

## Random Seed

In [100]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
tensor_a = torch.rand(3,3)

torch.manual_seed(RANDOM_SEED)
tensor_b = torch.rand(3,3)

print(tensor_a == tensor_b)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


## Differnce between a GPU tensor and a CPU tensor

A tensor can be both in GPU and CPU. But if we transfer it to GPU, we cannot transform the tensor into *Numpy array*.


In [12]:
import torch 
import numpy as np
tensor = torch.rand(2,2,device='cuda')
tensor = tensor.cpu().numpy()
tensor.device

'cpu'